<?php
/**
 * @var \Magento\Framework\View\Element\Html\Links $block
 */
?>
<div class="col-lg-3">
    <div class="footer-links-widget-text">
        <h3 class="footer-section-title"><?= $block->escapeHtml(__('CUSTOMER SERVICE')) ?></h3>
        <div class="footer_links">
            <ul>
                <?php foreach ($block->getLinks() as $link): ?>
                    <li><a href="<?= $link->getHref() ?>"><?= $link->getLabel() ?></a></li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>

