<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<li class="level0 nav-1 level-top ui-menu-item">
    <a href="<?php echo $this->getBaseUrl(); ?>" class="level-top ui-corner-all"  role="menuitem">
        <span><?= __("Home")?></span>
    </a>
</li>
<li class="level0 level-top ui-menu-item">
    <a href="<?php echo $this->getUrl('https://www.portotheme.com/magento2/porto/demo7_en/checkout/cart/'); ?>" class="level-top ui-corner-all"  role="menuitem">
        <span><?= __("Porto!")?></span>
    </a>
</li>
