<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use ICreative\Search\ViewModel\Search;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Search\Helper\Data;
use Magento\Search\ViewModel\ConfigProvider;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
?>
<?php
/** @var $escaper Escaper */
/** @var $block Template */
/** @var $helper Data */
/** @var $configProvider ConfigProvider */
/** @var $viewModel Search */
$viewModel = $block->getViewModel();
$helper = $this->helper(Data::class);
$configProvider = $block->getData('configProvider');
?>

<div class="block block-search">

    <div class="search-area">
        <a class="search-link">
			<span>
				<i class="icon-magnifier"></i>
			</span>
        </a>
        <div class="search-box"> <!-- search js scope-->
            <div class="block block-title"><strong><?= $block->escapeHtml(__('Search')) ?></strong></div>
            <div class="block block-content">
                <form class="form minisearch" id="search_mini_form"
                      action="<?= $block->escapeUrl($helper->getResultUrl()) ?>" method="get">
                    <div class="field search">
                        <div class="control">
                            <input id="search" data-bind="textInput: query"
                                <?php if ($configProvider->isSuggestionsAllowed()): ?>
                                    data-mage-init='{"quickSearch":{
                                    "formSelector":"#search_mini_form",
                                    "url":"<?= $block->escapeUrl($helper->getSuggestUrl()) ?>",
                                    "destinationSelector":"#search_autocomplete",
                                    "minSearchLength":"<?= $block->escapeHtml($helper->getMinQueryLength()) ?>"}
                               }'
                                <?php endif; ?>
                                   type="text"
                                   name="<?= $block->escapeHtmlAttr($helper->getQueryParamName()) ?>"
                                   value="<?= /* @noEscape */
                                   $helper->getEscapedQueryText() ?>"
                                   placeholder="<?= $block->escapeHtmlAttr(__('Search...')) ?>"
                                   class="input-text"
                                   maxlength="<?= $block->escapeHtmlAttr($helper->getMaxQueryLength()) ?>"
                                   role="combobox"
                                   aria-haspopup="false"
                                   aria-autocomplete="both"
                                   autocomplete="off"
                                   aria-expanded="true"/>
                            <div class="category-select">
                                <?php $categories = $viewModel->getActiveTopCategories(); ?>
                                <label for="categories-search-select">Select category</label>
                                <select name="categories" id="categories-search-select" data-bind="value: cat_id">
                                    <option selected="selected" value="0">All categories</option>
                                    <?php foreach ($categories as $category): ?>
                                        <option value="<?= $block->escapeHtmlAttr($category->getId()) ?>">
                                            <?= $block->escapeHtml($category->getName()) ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="actions">
                        <button type="submit"
                                title="<?= $block->escapeHtml(__('Search')) ?>"
                                class="action search"
                                aria-label="Search"
                        >
                        </button>
                    </div>
                </form>
            </div>
            <div class="search-results">
                <div data-bind="foreach: products">
                    <div class="autocomplete-suggestion">
                        <a class="search-product-link" data-bind="attr: { href: product_url}">
                            <div class="suggestion-left">
                                <img src="" alt="" data-bind="attr: { src: image_url, alt: name}"/>
                            </div>
                            <div class="suggestion-right">
                                <div class="product-line product-name" data-bind="text: name">
                                </div>
                                <div class="product-line product-sku" data-bind="text: sku">
                                </div>
                                <div class="product-line product-price">Price:
                                    <span data-bind="text: price"></span>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
