<?php
$url = $this->getURL('search/index/search');
$imageURL = $this->getUrl().'pub/media/catalog/product';
?>
<div id="result" data-bind="scope: 'ko-search'">

</div>
<script type="text/x-magento-init">
    {
        "*" : {
            "Magento_Ui/js/core/app": {
                "components": {
                    "ko-search": {
                        "component": "Demo_Search/js/ko-search",
                        "url": "<?=$url?>",
                        "imageurl": "<?=$imageURL?>"
                    }
                }
            }
        }
    }
</script>
