<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use ICreative\Search\ViewModel\Search;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Search\Helper\Data;
use Magento\Search\ViewModel\ConfigProvider;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
?>
<?php
/** @var $escaper Escaper */
/** @var $block Template */
/** @var $helper Data */
/** @var $configProvider ConfigProvider */
/** @var $viewModel Search */
$viewModel = $block->getViewModel();
$helper = $this->helper(Data::class);
$configProvider = $block->getData('configProvider');
?>
<div class="block block-search">

    <div class="search-area">
        <a class="search-link">
			<span>
				<i class="icon-magnifier"></i>
			</span>
        </a>
        <div class="search-box">
            <div class="block block-title"><strong><?= $block->escapeHtml(__('Search')) ?></strong></div>
            <div class="block block-content">
                <form class="form minisearch" id="search_mini_form"
                      action="<?= $block->escapeUrl($helper->getResultUrl()) ?>" method="get">
                    <div class="field search">
                        <label class="label" for="search" data-role="minisearch-label">
                            <span><?= $block->escapeHtml(__('Search')) ?></span>
                        </label>
                        <div class="control">
                            <input id="search"
                                <?php if ($configProvider->isSuggestionsAllowed()): ?>
                                    data-mage-init='{"quickSearch":{
                                    "formSelector":"#search_mini_form",
                                    "url":"<?= $block->escapeUrl($helper->getSuggestUrl()) ?>",
                                    "destinationSelector":"#search_autocomplete",
                                    "minSearchLength":"<?= $block->escapeHtml($helper->getMinQueryLength()) ?>"}
                               }'
                                <?php endif; ?>
                                   type="text"
                                   name="<?= $block->escapeHtmlAttr($helper->getQueryParamName()) ?>"
                                   value="<?= /* @noEscape */
                                   $helper->getEscapedQueryText() ?>"
                                   placeholder="<?= $block->escapeHtmlAttr(__('Search...')) ?>"
                                   class="input-text"
                                   maxlength="<?= $block->escapeHtmlAttr($helper->getMaxQueryLength()) ?>"
                                   role="combobox"
                                   aria-haspopup="false"
                                   aria-autocomplete="both"
                                   autocomplete="off"
                                   aria-expanded="false"/>
                            <div id="search_autocomplete" class="search-autocomplete"></div>
                            <?= $block->getChildHtml() ?>
                        </div>
                    </div>
                    <div class="actions">
                        <button type="submit"
                                title="<?= $block->escapeHtml(__('Search')) ?>"
                                class="action search"
                                aria-label="Search"
                        >
                            <span><?= $block->escapeHtml(__('Search')) ?></span>
                        </button>
                    </div>
                </form>
            </div>
            <div class="category-select">
                <?php $categories = $viewModel->getAllCategories(); ?>
                <label for="categories">Select category</label>
                <select name="categories" id="categories">
                    <?php foreach ($categories as $category): ?>
                        <option value="<?= $block->escapeHtmlAttr($category->getId()) ?>">
                            <?= $block->escapeHtml($category->getName()) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>

            <div class="search-results">
                Search result <br/>
                <?php
                $ids = [6];
                $categoryProducts = $viewModel->getProductCollectionByCategories($ids);
                ?>
                <?php foreach ($categoryProducts as $product): ?>
                    <img src="<?= $viewModel->getProductImageUrl($product); ?>"
                         alt="<?= $product->getName() ?>"/>
                    <a href="<?= $product->getProductUrl() ?>">
                        <?= $product->getName() ?>
                    </a>
                    <b><?= $product->getPrice() ?></b><br/>
                <?php endforeach; ?>


            </div>
        </div>
    </div>


</div>
