<table style="width: 100%;" border="0" cellspacing="0" cellpadding="7">
    <tbody>
    <tr>
        <td class="head">US Size</td>
        <td class="head">UK Size</td>
        <td class="head">European</td>
        <td class="head">Japanese</td>
    </tr>
    <tr>
        <td>4</td>
        <td>2</td>
        <td>35</td>
        <td>21</td>
    </tr>
    <tr>
        <td class="even">4.5</td>
        <td class="even">2.5</td>
        <td class="even">35.5</td>
        <td class="even">21.5</td>
    </tr>
    <tr>
        <td>5</td>
        <td>3</td>
        <td>36</td>
        <td>22</td>
    </tr>
    <tr>
        <td class="even">5.5</td>
        <td class="even">3.5</td>
        <td class="even">36.5</td>
        <td class="even">22.5</td>
    </tr>
    <tr>
        <td>6</td>
        <td>4</td>
        <td>37</td>
        <td>23</td>
    </tr>
    <tr>
        <td class="even">6.5</td>
        <td class="even">4.5</td>
        <td class="even">37.5</td>
        <td class="even">23.5</td>
    </tr>
    <tr>
        <td>7</td>
        <td>5</td>
        <td>38</td>
        <td>24</td>
    </tr>
    <tr>
        <td class="even">7.5</td>
        <td class="even">5.5</td>
        <td class="even">38.5</td>
        <td class="even">24.5</td>
    </tr>
    <tr>
        <td>8</td>
        <td>6</td>
        <td>39</td>
        <td>25</td>
    </tr>
    <tr>
        <td class="even">8.5</td>
        <td class="even">6.5</td>
        <td class="even">39.5</td>
        <td class="even">25.5</td>
    </tr>
    <tr>
        <td>9</td>
        <td>7</td>
        <td>40</td>
        <td>26</td>
    </tr>
    <tr>
        <td class="even">9.5</td>
        <td class="even">7.5</td>
        <td class="even">40.5</td>
        <td class="even">26.5</td>
    </tr>
    <tr>
        <td>10</td>
        <td>8</td>
        <td>41</td>
        <td>27</td>
    </tr>
    <tr>
        <td class="even">10.5</td>
        <td class="even">8.5</td>
        <td class="even">41.5</td>
        <td class="even">27.5</td>

    </tr>
    <tr>
        <td>11</td>
        <td>9</td>
        <td>42</td>
        <td>28</td>
    </tr>
    <tr>
        <td class="even">11.5</td>
        <td class="even">9.5</td>
        <td class="even">42.5</td>
        <td class="even">28.5</td>
    </tr>
    <tr>
        <td>12</td>
        <td>10</td>
        <td>43</td>
        <td>29</td>
    </tr>
    <tr>
        <td class="even">12.5</td>
        <td class="even">&nbsp;10.5</td>
        <td class="even">43.5</td>
        <td class="even">29.5</td>
    </tr>
    </tbody>
</table>


<script>
    tr:nth-child(even) {
        background-color: #f2f2f2;
    }
</script>
